import { useState } from "react";
import { Link } from "react-router-dom";
import SEO from "../components/SEO";
import { canonicalFor, SITE_URL } from "../data/seo";
import {
  CALENDAR_SUBSCRIPTION_PATH,
  CALENDAR_SUBSCRIPTION_STEPS,
  ICS_FEEDS,
  calendarSubscriptionFaqs,
  calendarSubscriptionMeta,
  googleCalendarUrl,
  webcalUrl,
} from "../data/icsFeeds";

const CopyButton = ({ text }) => {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      window.prompt("Kopioi osoite:", text);
    }
  };
  return (
    <button type="button" className="btn btn-ghost" onClick={copy}>
      {copied ? "Kopioitu ✓" : "Kopioi osoite"}
    </button>
  );
};

// Landing page for the /ics/*.ics subscription feeds (generated by
// prerender.js from icsFeeds.js — the same list this page renders).
const CalendarSubscription = () => {
  const faqs = calendarSubscriptionFaqs(new Date().getFullYear());

  return (
    <section className="app">
      <SEO {...calendarSubscriptionMeta} canonical={canonicalFor(CALENDAR_SUBSCRIPTION_PATH)} />
      <div className="breadcrumb">
        <Link to="/">Etusivu</Link> / Kalenteritilaus
      </div>

      <h1>Viikkonumerot ja pyhäpäivät omaan kalenteriisi</h1>

      <p className="lead">
        <span className="answer-sentence">
          Tilaa viikkonumerot, Suomen pyhäpäivät ja liputuspäivät Google-kalenteriin,
          Outlookiin tai iPhoneen yhdellä klikkauksella.
        </span>{" "}
        Tilaus on ilmainen ja päivittyy itsestään – uudet vuodet tulevat
        kalenteriin automaattisesti.
      </p>

      <div className="ics-feeds">
        {ICS_FEEDS.map((feed) => {
          const url = `${SITE_URL}${feed.path}`;
          return (
            <article key={feed.id} className="ics-card">
              <h2>{feed.name}</h2>
              <p>{feed.desc}</p>
              <code className="ics-url">{url}</code>
              <div className="ics-actions">
                <a
                  className="btn"
                  href={googleCalendarUrl(url)}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Lisää Google-kalenteriin
                </a>
                <a className="btn btn-ghost" href={webcalUrl(url)}>
                  Avaa kalenterisovelluksessa
                </a>
                <CopyButton text={url} />
              </div>
            </article>
          );
        })}
      </div>

      <section className="prose">
        <h2>Näin tilaat kalenterin</h2>
        {CALENDAR_SUBSCRIPTION_STEPS.map((group) => (
          <div key={group.app}>
            <h3>{group.app}</h3>
            <ol>
              {group.steps.map((s) => (
                <li key={s}>{s}</li>
              ))}
            </ol>
          </div>
        ))}
      </section>

      <section className="prose">
        <h2>Usein kysytyt kysymykset</h2>
        {faqs.map((item, index) => (
          <details key={item.q} open={index === 0}>
            <summary>{item.q}</summary>
            <p>{item.a}</p>
          </details>
        ))}
      </section>

      <p>
        Haluatko viikkonumeron omalle sivullesi? Katso{" "}
        <Link to="/upota-viikkonumero">viikkonumero-widget</Link>. Tiedot
        löytyvät myös <Link to="/avoin-data">avoimena JSON-datana</Link>.
      </p>
    </section>
  );
};

export default CalendarSubscription;
